### ISSUE TITLE
i found a error how can we fix it

### ISSUE THREAD

**Issue by Hamburgerboy15** [Adivise/NanoSpacePlus#20]
Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/NanoSpacePlus/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MainClient.login (/home/runner/NanoSpacePlus/node_modules/discord.js/src/client/Client.js:232:7) {
  code: 'DisallowedIntents'
}
MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/home/runner/NanoSpacePlus/node_modules/mongoose/lib/connection.js:847:32)
    at /home/runner/NanoSpacePlus/node_modules/mongoose/lib/index.js:351:10
    at /home/runner/NanoSpacePlus/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/runner/NanoSpacePlus/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/home/runner/NanoSpacePlus/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/home/runner/NanoSpacePlus/node_modules/mongoose/lib/index.js:350:20)
    at module.exports (/home/runner/NanoSpacePlus/handlers/Database/loadDatabase.js:6:24)
    at module.exports (/home/runner/NanoSpacePlus/handlers/loadDatabase.js:4:42)
    at /home/runner/NanoSpacePlus/nanospace.js:53:103
    at Array.forEach (<anonymous>)
    at new MainClient (/home/runner/NanoSpacePlus/nanospace.js:53:64)
    at Object.<anonymous> (/home/runner/NanoSpacePlus/index.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { '127.0.0.1:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}

**Comment by Adivise** [comment]
https://gist.github.com/Adivise/ed4425f52cad9fd29614e3e021e3e297
