### ISSUE TITLE
"Error loading track failed" when I search using spotify and apple music links

### ISSUE THREAD

**Issue by muralianand12345** [Adivise/NanoSpacePlus#26]

**Comment by muralianand12345** [comment]
`DiscordAPIError[10008]: Unknown Message
    at SequentialHandler.runRequest (/home/murali/NanoSpacePlus/node_modules/@discordjs/rest/dist/index.js:667:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (/home/murali/NanoSpacePlus/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/home/murali/NanoSpacePlus/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async MessageManager.delete (/home/murali/NanoSpacePlus/node_modules/discord.js/src/managers/MessageManager.js:254:5)
    at async Message.delete (/home/murali/NanoSpacePlus/node_modules/discord.js/src/structures/Message.js:784:5) {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Unknown Message', code: 10008 },
  code: 10008,
  status: 404,
  method: 'DELETE',
  url: 'https://discord.com/api/v10/channels/1073287827661537410/messages/1074383428688019566'
}
`

**Comment by Adivise** [comment]
must install lavalink plugins https://github.com/TopiSenpai/LavaSrc
