### ISSUE TITLE
"channel.isTextBased is not a function" ERROR

### ISSUE THREAD

**Issue by muralianand12345** [Adivise/NanoSpacePlus#27]
**Error when someone plays a song using command or uses play command buttons.** 

`TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (/home/murali/NanoSpacePlus/node_modules/discord.js/src/client/actions/InteractionCreate.js:50:33)
    at module.exports [as INTERACTION_CREATE] (/home/murali/NanoSpacePlus/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/murali/NanoSpacePlus/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/murali/NanoSpacePlus/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/murali/NanoSpacePlus/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/home/murali/NanoSpacePlus/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/murali/NanoSpacePlus/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/murali/NanoSpacePlus/node_modules/ws/lib/websocket.js:1180:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/murali/NanoSpacePlus/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/home/murali/NanoSpacePlus/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/home/murali/NanoSpacePlus/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/home/murali/NanoSpacePlus/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)`

**Comment by NitrixEXE** [comment]
If you're getting the following error with interactions:

```js
TypeError: channel.isTextBased is not a function // v14
TypeError: channel.isText is not a function // v13
```

Discord rolled out the breaking change with interactions from a month ago.  The library has been updated to handle it, but you need to update it.  Please update to the latest version of discord.js for your major version.

v13 users: Use v13.14.0 or newer `npm i discord.js@v13-lts`
v14 users: Use v14.8.0 or newer `npm i discord.js@latest`
