### ISSUE TITLE
on play command

### ISSUE THREAD

**Issue by Dectectable** [Adivise/NanoSpacePlus#4]
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (/mnt/privatexd/node_modules/petitio/dist/index.js:30:574)
    at ke.json (/mnt/privatexd/node_modules/petitio/dist/index.js:30:2499)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Adivise** [comment]
this error from the `library(module)` i can't fixed this!

**Comment by RainyXeon** [comment]
@Dectectable you can use `npm start` or `yarn start` to use `node v17`. Because this issue is from elerajs not integrated with `node v18`. MenuDocs will fix soon.
